/**
 * Journey Heizungstausch, sieben Schritte.
 * Kanonische Seite: /heizung/heizungskonfigurator. Texte in Kundensprache.
 */
import { ANLAGENALTER_OPTIONEN, STANDORT_HEIZUNG_OPTIONEN, type Journey } from './typen';

export const heizungJourney: Journey = {
  id: 'heizung',
  name: 'Neue Heizung',
  pfad: '/heizung/heizungskonfigurator',
  quelle: 'web_heizung',
  gewerk: 'heizung',
  ueberschrift: 'Ihre neue Heizung',
  unterzeile: 'Sieben kurze Fragen. Danach kennen wir Ihr Haus und sagen Ihnen, was der Staat dazuzahlt.',
  zusage:
    'Ihr Haus verdient eine Lösung, die passt. Ein Meister prüft Ihre Angaben und meldet sich innerhalb von zwei Werktagen mit einer Kostenschätzung.',
  standardAntworten: {
    journey: 'heizung',
    heutig: 'gas',
    alter: 'unbekannt',
    tanks: 0,
    gebaeude: 'efh',
    wohnflaeche: 140,
    baujahr: '1978_1995',
    verteilung: 'heizkoerper',
    heizkoerperTausch: 0,
    ziel: 'waermepumpe',
    raeume: 3,
    selbstBewohnt: true,
    einkommenUnterGrenze: false,
    personen: 2,
    verbrauchJahr: null,
    standortHeizung: 'unbekannt',
  },
  schritte: [
    {
      id: 'heute',
      titel: 'Was heizt heute',
      art: 'fragen',
      frage: 'Womit heizen Sie heute?',
      erklaerung: 'Wenn Sie unsicher sind, wählen Sie das, was am ehesten zutrifft.',
      fragen: [
        {
          id: 'heutig',
          ziel: 'antworten',
          feld: 'heutig',
          art: 'einzelauswahl',
          frage: 'Ihre heutige Heizung',
          fehler: 'Bitte wählen Sie Ihre heutige Heizung.',
          spalten: 3,
          optionen: [
            { wert: 'gas', titel: 'Gas', untertitel: 'Anschluss im Haus', piktogramm: 'gas' },
            { wert: 'oel', titel: 'Öl', untertitel: 'Mit Tanks im Keller', piktogramm: 'oel' },
            { wert: 'strom', titel: 'Strom', untertitel: 'Zum Beispiel Nachtspeicher', piktogramm: 'strom' },
            { wert: 'holz', titel: 'Holz oder Pellets', untertitel: 'Kessel oder Ofen', piktogramm: 'holz' },
            { wert: 'sonstiges', titel: 'Etwas anderes', untertitel: 'Sagen Sie es uns im Gespräch', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'alter',
          ziel: 'antworten',
          feld: 'alter',
          art: 'einzelauswahl',
          frage: 'Wie alt ist die Anlage ungefähr?',
          fehler: 'Bitte wählen Sie ein Alter.',
          optionen: ANLAGENALTER_OPTIONEN,
        },
        {
          id: 'tanks',
          ziel: 'antworten',
          feld: 'tanks',
          art: 'anzahl',
          frage: 'Wie viele Tanks stehen im Keller?',
          erklaerung: 'Die alten Tanks holen wir heraus und entsorgen sie.',
          min: 0,
          max: 6,
          einheit: 'Tanks',
          sichtbarWenn: { feld: 'heutig', werte: ['oel'] },
        },
        {
          id: 'verbrauchJahr',
          ziel: 'antworten',
          feld: 'verbrauchJahr',
          art: 'zahl',
          frage: 'Was steht auf Ihrer letzten Abrechnung?',
          erklaerung:
            'Bei Gas in Kilowattstunden, bei Öl in Litern. Wenn Sie es nicht wissen, lassen Sie das Feld frei.',
          min: 0,
          max: 60_000,
          schritt: 100,
          einheit: 'kWh im Jahr',
          eingabe: 'feld',
          optional: true,
          sichtbarWenn: { feld: 'heutig', werte: ['gas', 'strom', 'holz', 'sonstiges'] },
        },
        {
          id: 'verbrauchJahrOel',
          ziel: 'antworten',
          feld: 'verbrauchJahr',
          art: 'zahl',
          frage: 'Was steht auf Ihrer letzten Abrechnung?',
          erklaerung:
            'Bei Gas in Kilowattstunden, bei Öl in Litern. Wenn Sie es nicht wissen, lassen Sie das Feld frei.',
          min: 0,
          max: 20_000,
          schritt: 100,
          einheit: 'Liter im Jahr',
          eingabe: 'feld',
          optional: true,
          sichtbarWenn: { feld: 'heutig', werte: ['oel'] },
        },
        {
          id: 'standortHeizung',
          ziel: 'antworten',
          feld: 'standortHeizung',
          art: 'einzelauswahl',
          frage: 'Wo steht die Heizung heute?',
          fehler: 'Bitte wählen Sie einen Standort.',
          spalten: 3,
          optionen: STANDORT_HEIZUNG_OPTIONEN,
        },
      ],
    },
    {
      id: 'haus',
      titel: 'Ihr Haus',
      art: 'fragen',
      frage: 'Erzählen Sie uns von Ihrem Haus',
      fragen: [
        {
          id: 'gebaeude',
          ziel: 'antworten',
          feld: 'gebaeude',
          art: 'einzelauswahl',
          frage: 'Um welches Gebäude geht es?',
          fehler: 'Bitte wählen Sie einen Gebäudetyp.',
          optionen: [
            { wert: 'efh', titel: 'Einfamilienhaus', piktogramm: 'haus' },
            { wert: 'dhh', titel: 'Doppelhaushälfte', piktogramm: 'doppelhaus' },
            { wert: 'rh', titel: 'Reihenhaus', piktogramm: 'reihenhaus' },
            { wert: 'mfh', titel: 'Haus mit mehreren Wohnungen', piktogramm: 'mehrfamilienhaus' },
          ],
        },
        {
          id: 'wohnflaeche',
          ziel: 'antworten',
          feld: 'wohnflaeche',
          art: 'zahl',
          frage: 'Wie viel Wohnfläche wird beheizt?',
          erklaerung: 'Eine Schätzung genügt.',
          min: 30,
          max: 600,
          schritt: 5,
          einheit: 'Quadratmeter',
        },
        {
          id: 'baujahr',
          ziel: 'antworten',
          feld: 'baujahr',
          art: 'einzelauswahl',
          frage: 'Aus welcher Zeit stammt das Haus?',
          fehler: 'Bitte wählen Sie eine Bauzeit.',
          optionen: [
            { wert: 'vor_1978', titel: 'Vor 1978', untertitel: 'Häufig noch ohne Dämmung', piktogramm: 'baujahr-alt' },
            { wert: '1978_1995', titel: '1978 bis 1995', untertitel: 'Erste Dämmung vorhanden', piktogramm: 'baujahr-mittel' },
            { wert: '1996_2015', titel: '1996 bis 2015', untertitel: 'Gut gedämmt', piktogramm: 'baujahr-neu' },
            { wert: 'ab_2016', titel: 'Ab 2016', untertitel: 'Neubaustandard', piktogramm: 'baujahr-neubau' },
          ],
        },
        {
          id: 'wohneinheiten',
          ziel: 'objekt',
          feld: 'wohneinheiten',
          art: 'anzahl',
          frage: 'Wie viele Wohnungen versorgt die Heizung?',
          erklaerung: 'Je Wohnung steigt der Betrag, den der Staat fördert.',
          min: 1,
          max: 12,
          einheit: 'Wohnungen',
        },
        {
          id: 'personen',
          ziel: 'antworten',
          feld: 'personen',
          art: 'anzahl',
          frage: 'Wie viele Personen leben im Haus?',
          erklaerung: 'Davon hängt die Größe des Warmwasserspeichers ab.',
          min: 1,
          max: 12,
          einheit: 'Personen',
        },
      ],
    },
    {
      id: 'verteilung',
      titel: 'Wärme im Raum',
      art: 'fragen',
      frage: 'Wie kommt die Wärme heute in Ihre Räume?',
      fragen: [
        {
          id: 'verteilung',
          ziel: 'antworten',
          feld: 'verteilung',
          art: 'einzelauswahl',
          frage: 'Ihre Wärme im Raum',
          fehler: 'Bitte wählen Sie eine Angabe.',
          spalten: 3,
          optionen: [
            { wert: 'heizkoerper', titel: 'Über Heizkörper', untertitel: 'An den Wänden, meist unter dem Fenster', piktogramm: 'heizkoerper' },
            { wert: 'fussboden', titel: 'Über den Fußboden', untertitel: 'Warme Flächen im ganzen Raum', piktogramm: 'fussbodenheizung' },
            { wert: 'gemischt', titel: 'Beides gemischt', untertitel: 'Je nach Raum verschieden', piktogramm: 'gemischt' },
          ],
        },
        {
          id: 'heizkoerperTausch',
          ziel: 'antworten',
          feld: 'heizkoerperTausch',
          art: 'anzahl',
          frage: 'Wie viele Heizkörper sollen neu werden?',
          erklaerung: 'Null bedeutet, alle bleiben, wie sie sind.',
          min: 0,
          max: 30,
          einheit: 'Heizkörper',
          sichtbarWenn: { feld: 'verteilung', werte: ['heizkoerper', 'gemischt'] },
        },
      ],
    },
    {
      id: 'ziel',
      titel: 'Zukunft',
      art: 'fragen',
      frage: 'Was soll künftig heizen?',
      erklaerung: 'Sie müssen sich nicht festlegen. Wir sagen Ihnen ehrlich, was zu Ihrem Haus passt.',
      fragen: [
        {
          id: 'ziel',
          ziel: 'antworten',
          feld: 'ziel',
          art: 'einzelauswahl',
          frage: 'Ihr Wunsch für die Zukunft',
          fehler: 'Bitte wählen Sie eine Richtung.',
          optionen: [
            { wert: 'waermepumpe', titel: 'Wärmepumpe', untertitel: 'Wärme aus der Luft, hoch gefördert', piktogramm: 'waermepumpe' },
            { wert: 'klima', titel: 'Klimaanlage, die im Winter auch heizt', untertitel: 'Im Sommer kühl, im Winter warm', piktogramm: 'klima' },
            { wert: 'gas_neu', titel: 'Neue Gasheizung', untertitel: 'Bewährte Technik, kleiner Eingriff', piktogramm: 'gasheizung' },
            { wert: 'unklar', titel: 'Beraten Sie mich', untertitel: 'Wir vergleichen die Wege für Sie', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'raeume',
          ziel: 'antworten',
          feld: 'raeume',
          art: 'anzahl',
          frage: 'Wie viele Räume sollen versorgt werden?',
          min: 1,
          max: 8,
          einheit: 'Räume',
          sichtbarWenn: { feld: 'ziel', werte: ['klima'] },
        },
      ],
    },
    {
      id: 'foerderung',
      titel: 'Zuschuss',
      art: 'fragen',
      frage: 'Wie viel zahlt der Staat dazu?',
      erklaerung: 'Zwei Fragen genügen, damit wir Ihren Zuschuss einschätzen können.',
      fragen: [
        {
          id: 'selbstBewohnt',
          ziel: 'antworten',
          feld: 'selbstBewohnt',
          art: 'einzelauswahl',
          frage: 'Wohnen Sie selbst in dem Haus?',
          fehler: 'Bitte wählen Sie eine Angabe.',
          optionen: [
            { wert: true, titel: 'Ja, ich wohne hier', piktogramm: 'eigentum' },
            { wert: false, titel: 'Nein, es ist vermietet', piktogramm: 'miete' },
          ],
        },
        {
          id: 'einkommenUnterGrenze',
          ziel: 'antworten',
          feld: 'einkommenUnterGrenze',
          art: 'einzelauswahl',
          frage: 'Liegt Ihr zu versteuerndes Haushaltseinkommen unter 40.000 Euro im Jahr?',
          erklaerung: 'Diese Angabe entscheidet über einen zusätzlichen Zuschuss. Nachweise brauchen wir erst später.',
          fehler: 'Bitte wählen Sie eine Angabe.',
          optionen: [
            { wert: true, titel: 'Ja', piktogramm: 'ja' },
            { wert: false, titel: 'Nein oder noch offen', piktogramm: 'nein' },
          ],
        },
      ],
    },
    {
      id: 'haus_zeit',
      titel: 'Haus und Zeit',
      art: 'fragen',
      frage: 'Noch zwei Angaben zum Haus',
      fragen: [
        {
          id: 'eigentum',
          ziel: 'objekt',
          feld: 'eigentum',
          art: 'einzelauswahl',
          frage: 'Gehört Ihnen das Haus?',
          fehler: 'Bitte wählen Sie eine Angabe.',
          spalten: 3,
          optionen: [
            { wert: 'eigentum', titel: 'Ja, mir', untertitel: 'Ich entscheide selbst', piktogramm: 'eigentum' },
            { wert: 'miete', titel: 'Nein, gemietet', untertitel: 'Die Eigentümerin oder der Eigentümer entscheidet mit', piktogramm: 'miete' },
            { wert: 'unklar', titel: 'Noch offen', untertitel: 'Klären wir gemeinsam', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'plz',
          ziel: 'objekt',
          feld: 'plz',
          art: 'text',
          frage: 'Postleitzahl des Hauses',
          erklaerung: 'Wir arbeiten rund um Wetzlar und im Lahn Dill Kreis.',
          fehler: 'Bitte geben Sie eine fünfstellige Postleitzahl an.',
          platzhalter: '35576',
          maxLaenge: 5,
          eingabemodus: 'numeric',
        },
        {
          id: 'dringlichkeit',
          ziel: 'meta',
          feld: 'dringlichkeit',
          art: 'einzelauswahl',
          frage: 'Wann soll es losgehen?',
          fehler: 'Bitte wählen Sie einen Zeitraum.',
          optionen: [
            { wert: 'sofort', titel: 'So schnell wie möglich', untertitel: 'Die Heizung macht Sorgen', piktogramm: 'sofort' },
            { wert: 'wochen_4', titel: 'In den nächsten Wochen', piktogramm: 'kalender' },
            { wert: 'monate_3', titel: 'In den nächsten Monaten', piktogramm: 'uhr' },
            { wert: 'unklar', titel: 'Noch offen', piktogramm: 'fragezeichen' },
          ],
        },
      ],
    },
    {
      id: 'kontakt',
      titel: 'Ergebnis und Kontakt',
      art: 'kontakt',
      fragen: [],
    },
  ],
};

export default heizungJourney;
