/**
 * Journey Wärmepumpen-Check, sieben Schritte.
 * Seite: /heizung/waermepumpe/check. Beantwortet die Frage, ob eine Wärmepumpe
 * zum Haus passt. Deterministische Eignungsregeln, keine Eurobeträge im Datensatz.
 */
import { ANLAGENALTER_OPTIONEN, STANDORT_HEIZUNG_OPTIONEN, type Journey } from './typen';

export const waermepumpeJourney: Journey = {
  id: 'waermepumpe',
  name: 'Wärmepumpen-Check',
  pfad: '/heizung/waermepumpe/check',
  quelle: 'web_wp',
  gewerk: 'solar',
  ueberschrift: 'Passt eine Wärmepumpe zu Ihrem Haus?',
  unterzeile: 'Sieben kurze Fragen. Sie erhalten sofort eine ehrliche Einschätzung.',
  zusage:
    'Ihr Haus schauen wir uns genauer an. Ein Meister meldet sich innerhalb von zwei Werktagen und sagt Ihnen, was möglich ist.',
  standardAntworten: {
    journey: 'waermepumpe',
    heutig: 'gas',
    baujahr: '1978_1995',
    wohnflaeche: 140,
    verteilung: 'heizkoerper',
    komfort: 'heizen',
    selbstBewohnt: true,
    einkommenUnterGrenze: false,
    alter: 'unbekannt',
    personen: 2,
    verbrauchJahr: null,
    standortHeizung: 'unbekannt',
  },
  schritte: [
    {
      id: 'heute',
      titel: 'Was heizt heute',
      art: 'fragen',
      frage: 'Womit heizen Sie heute?',
      fragen: [
        {
          id: 'heutig',
          ziel: 'antworten',
          feld: 'heutig',
          art: 'einzelauswahl',
          frage: 'Ihre heutige Heizung',
          fehler: 'Bitte wählen Sie Ihre heutige Heizung.',
          spalten: 3,
          optionen: [
            { wert: 'gas', titel: 'Gas', untertitel: 'Anschluss im Haus', piktogramm: 'gas' },
            { wert: 'oel', titel: 'Öl', untertitel: 'Mit Tanks im Keller', piktogramm: 'oel' },
            { wert: 'strom', titel: 'Strom', untertitel: 'Zum Beispiel Nachtspeicher', piktogramm: 'strom' },
            { wert: 'holz', titel: 'Holz oder Pellets', untertitel: 'Kessel oder Ofen', piktogramm: 'holz' },
            { wert: 'sonstiges', titel: 'Etwas anderes', untertitel: 'Sagen Sie es uns im Gespräch', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'alter',
          ziel: 'antworten',
          feld: 'alter',
          art: 'einzelauswahl',
          frage: 'Wie alt ist die Heizung?',
          fehler: 'Bitte wählen Sie ein Alter.',
          optionen: ANLAGENALTER_OPTIONEN,
        },
        {
          id: 'verbrauchJahr',
          ziel: 'antworten',
          feld: 'verbrauchJahr',
          art: 'zahl',
          frage: 'Was steht auf Ihrer letzten Abrechnung?',
          erklaerung:
            'Bei Gas und Strom in Kilowattstunden. Wenn Sie es nicht wissen, lassen Sie das Feld frei.',
          min: 0,
          max: 60_000,
          schritt: 100,
          einheit: 'kWh im Jahr',
          eingabe: 'feld',
          optional: true,
          sichtbarWenn: { feld: 'heutig', werte: ['gas', 'strom', 'sonstiges'] },
        },
        {
          id: 'verbrauchJahrOel',
          ziel: 'antworten',
          feld: 'verbrauchJahr',
          art: 'zahl',
          frage: 'Was steht auf Ihrer letzten Abrechnung?',
          erklaerung:
            'Die Menge Heizöl, die Sie im Jahr tanken. Wenn Sie es nicht wissen, lassen Sie das Feld frei.',
          min: 0,
          max: 20_000,
          schritt: 100,
          einheit: 'Liter im Jahr',
          eingabe: 'feld',
          optional: true,
          sichtbarWenn: { feld: 'heutig', werte: ['oel'] },
        },
        {
          // Eigene Frage je Brennstoff: eine Kilowattstundenzahl im Holzfeld waere um den Faktor
          // des Heizwerts falsch und wuerde Heizlast und Betriebskosten unbrauchbar machen.
          id: 'verbrauchJahrHolz',
          ziel: 'antworten',
          feld: 'verbrauchJahr',
          art: 'zahl',
          frage: 'Wie viel Holz verbrauchen Sie im Jahr?',
          erklaerung:
            'In Raummetern. Wenn Sie mit Pellets heizen oder es nicht wissen, lassen Sie das Feld frei.',
          min: 0,
          max: 60,
          schritt: 1,
          einheit: 'Raummeter im Jahr',
          einheitEinzahl: 'Raummeter im Jahr',
          eingabe: 'feld',
          optional: true,
          sichtbarWenn: { feld: 'heutig', werte: ['holz'] },
        },
        {
          id: 'standortHeizung',
          ziel: 'antworten',
          feld: 'standortHeizung',
          art: 'einzelauswahl',
          frage: 'Wo steht die Heizung heute?',
          fehler: 'Bitte wählen Sie einen Standort.',
          spalten: 3,
          optionen: STANDORT_HEIZUNG_OPTIONEN,
        },
      ],
    },
    {
      id: 'haus',
      titel: 'Bauzeit und Fläche',
      art: 'fragen',
      frage: 'Aus welcher Zeit stammt das Haus?',
      erklaerung: 'Bauzeit und Fläche sagen viel darüber, wie gut eine Wärmepumpe arbeitet.',
      fragen: [
        {
          id: 'baujahr',
          ziel: 'antworten',
          feld: 'baujahr',
          art: 'einzelauswahl',
          frage: 'Bauzeit des Hauses',
          fehler: 'Bitte wählen Sie eine Bauzeit.',
          optionen: [
            { wert: 'vor_1978', titel: 'Vor 1978', untertitel: 'Häufig noch ohne Dämmung', piktogramm: 'baujahr-alt' },
            { wert: '1978_1995', titel: '1978 bis 1995', untertitel: 'Erste Dämmung vorhanden', piktogramm: 'baujahr-mittel' },
            { wert: '1996_2015', titel: '1996 bis 2015', untertitel: 'Gut gedämmt', piktogramm: 'baujahr-neu' },
            { wert: 'ab_2016', titel: 'Ab 2016', untertitel: 'Neubaustandard', piktogramm: 'baujahr-neubau' },
          ],
        },
        {
          id: 'wohnflaeche',
          ziel: 'antworten',
          feld: 'wohnflaeche',
          art: 'zahl',
          frage: 'Wie viel Wohnfläche wird beheizt?',
          erklaerung: 'Eine Schätzung genügt.',
          min: 30,
          max: 600,
          schritt: 5,
          einheit: 'Quadratmeter',
        },
        {
          id: 'personen',
          ziel: 'antworten',
          feld: 'personen',
          art: 'anzahl',
          frage: 'Wie viele Personen leben im Haus?',
          erklaerung: 'Davon hängt die Größe des Warmwasserspeichers ab.',
          min: 1,
          max: 12,
          einheit: 'Personen',
          einheitEinzahl: 'Person',
        },
      ],
    },
    {
      id: 'verteilung',
      titel: 'Wärme im Raum',
      art: 'fragen',
      frage: 'Wie kommt die Wärme heute in Ihre Räume?',
      fragen: [
        {
          id: 'verteilung',
          ziel: 'antworten',
          feld: 'verteilung',
          art: 'einzelauswahl',
          frage: 'Ihre Wärme im Raum',
          fehler: 'Bitte wählen Sie eine Angabe.',
          spalten: 3,
          optionen: [
            { wert: 'heizkoerper', titel: 'Über Heizkörper', untertitel: 'An den Wänden, meist unter dem Fenster', piktogramm: 'heizkoerper' },
            { wert: 'fussboden', titel: 'Über den Fußboden', untertitel: 'Warme Flächen im ganzen Raum', piktogramm: 'fussbodenheizung' },
            { wert: 'gemischt', titel: 'Beides gemischt', untertitel: 'Je nach Raum verschieden', piktogramm: 'gemischt' },
          ],
        },
      ],
    },
    {
      id: 'komfort',
      titel: 'Komfort',
      art: 'fragen',
      frage: 'Was soll die Anlage können?',
      fragen: [
        {
          id: 'komfort',
          ziel: 'antworten',
          feld: 'komfort',
          art: 'einzelauswahl',
          frage: 'Ihr Wunschkomfort',
          fehler: 'Bitte wählen Sie eine Angabe.',
          spalten: 3,
          optionen: [
            { wert: 'heizen', titel: 'Nur heizen', untertitel: 'Warme Räume im Winter', piktogramm: 'waerme' },
            { wert: 'heizen_kuehlen', titel: 'Heizen und kühlen', untertitel: 'Im Sommer angenehm kühl', piktogramm: 'kuehlen' },
            { wert: 'heizen_kuehlen_warmwasser', titel: 'Heizen, kühlen und Warmwasser', untertitel: 'Auch das Wasser für Bad und Küche', piktogramm: 'warmwasser' },
          ],
        },
      ],
    },
    {
      id: 'foerderung',
      titel: 'Zuschuss',
      art: 'fragen',
      frage: 'Wie viel zahlt der Staat dazu?',
      erklaerung: 'Zwei Fragen genügen, damit wir Ihren Zuschuss einschätzen können.',
      fragen: [
        {
          id: 'selbstBewohnt',
          ziel: 'antworten',
          feld: 'selbstBewohnt',
          art: 'einzelauswahl',
          frage: 'Wohnen Sie selbst im Haus?',
          fehler: 'Bitte wählen Sie eine Angabe.',
          optionen: [
            { wert: true, titel: 'Ja, ich wohne hier', piktogramm: 'eigentum' },
            { wert: false, titel: 'Nein, es ist vermietet', piktogramm: 'miete' },
          ],
        },
        {
          id: 'einkommenUnterGrenze',
          ziel: 'antworten',
          feld: 'einkommenUnterGrenze',
          art: 'einzelauswahl',
          frage: 'Liegt das Haushaltseinkommen unter 40.000 Euro im Jahr?',
          erklaerung: 'Wenn ja, zahlt der Staat mehr dazu. Nachweise brauchen wir erst später.',
          fehler: 'Bitte wählen Sie eine Angabe.',
          optionen: [
            { wert: true, titel: 'Ja', piktogramm: 'ja' },
            { wert: false, titel: 'Nein oder noch offen', piktogramm: 'nein' },
          ],
        },
      ],
    },
    {
      id: 'zeit',
      titel: 'Zeit',
      art: 'fragen',
      frage: 'Wann soll es losgehen?',
      fragen: [
        {
          id: 'dringlichkeit',
          ziel: 'meta',
          feld: 'dringlichkeit',
          art: 'einzelauswahl',
          frage: 'Ihr Zeitraum',
          fehler: 'Bitte wählen Sie einen Zeitraum.',
          optionen: [
            { wert: 'sofort', titel: 'So schnell wie möglich', untertitel: 'Die Heizung macht Sorgen', piktogramm: 'sofort' },
            { wert: 'wochen_4', titel: 'In den nächsten Wochen', piktogramm: 'kalender' },
            { wert: 'monate_3', titel: 'In den nächsten Monaten', piktogramm: 'uhr' },
            { wert: 'unklar', titel: 'Noch offen', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'eigentum',
          ziel: 'objekt',
          feld: 'eigentum',
          art: 'einzelauswahl',
          frage: 'Gehört Ihnen das Haus?',
          fehler: 'Bitte wählen Sie eine Angabe.',
          spalten: 3,
          optionen: [
            { wert: 'eigentum', titel: 'Ja, mir', untertitel: 'Ich entscheide selbst', piktogramm: 'eigentum' },
            { wert: 'miete', titel: 'Nein, gemietet', untertitel: 'Die Eigentümerin oder der Eigentümer entscheidet mit', piktogramm: 'miete' },
            { wert: 'unklar', titel: 'Noch offen', untertitel: 'Klären wir gemeinsam', piktogramm: 'fragezeichen' },
          ],
        },
        {
          id: 'plz',
          ziel: 'objekt',
          feld: 'plz',
          art: 'text',
          frage: 'Postleitzahl des Hauses',
          erklaerung: 'Wir arbeiten rund um Wetzlar und im Lahn Dill Kreis.',
          fehler: 'Bitte geben Sie eine fünfstellige Postleitzahl an.',
          platzhalter: '35576',
          maxLaenge: 5,
          eingabemodus: 'numeric',
        },
      ],
    },
    {
      id: 'kontakt',
      titel: 'Ergebnis und Kontakt',
      art: 'kontakt',
      fragen: [],
    },
  ],
};

export default waermepumpeJourney;
